<a href="https://colab.research.google.com/github/Krupa-1010/Deep_Learning/blob/main/Into_to_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Tensor


In [ ]:
import torch

In [ ]:
tensor=torch.randn(3,6)
tensor

tensor([[ 0.8583,  1.6691, -0.4880,  1.4326, -0.4127, -0.9598],
        [ 1.6613, -0.0925, -0.3319,  2.0958,  1.9515, -0.6550],
        [ 0.1397,  0.3576,  0.0935, -0.0062,  0.2750,  1.2806]])

In [ ]:
tensor_3d=torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
import numpy as np
arr=np.array([[2,3,4],[5,6,7]])
new_tensor=torch.tensor(arr)
new_tensor



torch.int64

Tensor Operations

In [14]:
my_torch=torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
#Reshape
my_torch=my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [18]:
#reshape if dont know the no of items
trch2=torch.arange(10)
trch2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
trch2=trch2.reshape(-1,5)
trch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [27]:
trc3=torch.arange(10)
trc3
trc3[2]=9
trc3

tensor([0, 1, 9, 3, 4, 5, 6, 7, 8, 9])

In [28]:
trc3=trc3.view(2,5)
trc3

tensor([[0, 1, 9, 3, 4],
        [5, 6, 7, 8, 9]])

In [29]:
#slice
print(trc3[:,1])

tensor([1, 6])


In [30]:
#return column
print(trc3[:,1:])

tensor([[1, 9, 3, 4],
        [6, 7, 8, 9]])


Tensor Math Operations

In [31]:
tensor1=torch.tensor([1,2,3,4])
tensor2=torch.tensor([5,6,7,8])

In [32]:
#addition
tensor1+tensor2

tensor([ 6,  8, 10, 12])

In [33]:
#addition longhand
torch.add(tensor1,tensor2)

tensor([ 6,  8, 10, 12])

In [35]:
#subract
tensor1-tensor2
#or
torch.sub(tensor1,tensor2)

tensor([-4, -4, -4, -4])

In [37]:
tensor1 * tensor2
#or
tensor1.mul(tensor2)

tensor([ 5, 12, 21, 32])

In [38]:
tensor1 / tensor2

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [40]:
tensor2 % tensor1
#or
torch.remainder(tensor2,tensor1)

tensor([0, 0, 1, 0])

In [41]:
#EXPONEnt
torch.pow(tensor1,2)

tensor([ 1,  4,  9, 16])

In [43]:
#reassignment(_)
tensor1=tensor1+tensor2
tensor1

tensor([11, 14, 17, 20])

In [44]:
tensor1.add_(tensor2)
tensor1

tensor([16, 20, 24, 28])